# Generated by Django 4.2.11 on 2026-01-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_location',
            field=models.CharField(blank=True, help_text='Current delivery location (e.g., "In transit - Wuse 2, Abuja")', max_length=200),
        ),
    ]
