# Generated by Django 4.2.11 on 2025-12-27 17:42

from django.db import migrations


def approve_existing_comments(apps, schema_editor):
    """Approve all existing comments so they appear on the website."""
    BlogComment = apps.get_model('blog', 'BlogComment')
    BlogComment.objects.filter(is_approved=False).update(is_approved=True)


def reverse_approve_comments(apps, schema_editor):
    """Reverse: Set all comments back to unapproved (optional, for rollback)."""
    BlogComment = apps.get_model('blog', 'BlogComment')
    BlogComment.objects.filter(is_approved=True).update(is_approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcomment_options_blogcomment_parent_and_more'),
    ]

    operations = [
        migrations.RunPython(approve_existing_comments, reverse_approve_comments),
    ]
