# Generated by Django 4.2.11 on 2025-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_approve_existing_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Comments are approved by default but can be moderated'),
        ),
    ]
