# Generated by Django 4.2.11 on 2025-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_catering_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringpackage',
            name='menu_options',
            field=models.JSONField(blank=True, default=list, help_text='List or groups of menu options'),
        ),
    ]
