# Generated by Django 4.2.11 on 2025-12-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Gallery Categories'},
        ),
    ]
