# Generated by Django 4.2.11 on 2026-01-12 20:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('6months', '6 Months Package'), ('3months', '3 Months Package'), ('1month', '1 Month Package'), ('2weeks', '2 Weeks Package')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if price varies or contact for pricing', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_for_beginners', models.BooleanField(default=False, help_text='For beginners')),
                ('is_advanced', models.BooleanField(default=False, help_text='Advanced classes')),
                ('is_upgrade', models.BooleanField(default=False, help_text='Upgrade package')),
                ('is_housewife', models.BooleanField(default=False, help_text='House-Wife package')),
                ('features', models.JSONField(default=list, help_text='List of features/inclusions for this package')),
                ('includes_theory', models.BooleanField(default=False)),
                ('theory_topics', models.JSONField(default=list, help_text='List of theory topics (e.g., F&B, kitchen management, costing)')),
                ('includes_pastries', models.BooleanField(default=False)),
                ('includes_baking', models.BooleanField(default=False)),
                ('includes_local_dishes', models.BooleanField(default=False)),
                ('includes_intercontinental', models.BooleanField(default=False)),
                ('includes_advanced_cooking', models.BooleanField(default=False)),
                ('includes_upscale_dining', models.BooleanField(default=False)),
                ('includes_event_catering', models.BooleanField(default=False)),
                ('includes_management', models.BooleanField(default=False)),
                ('includes_general_kitchen_mgmt', models.BooleanField(default=False)),
                ('includes_popular_african_menu', models.BooleanField(default=False)),
                ('includes_certification', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (lower numbers first)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='training/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Package',
                'verbose_name_plural': 'Training Packages',
                'ordering': ['display_order', 'package_type'],
            },
        ),
    ]
