# Generated by Django 4.2.11 on 2026-01-12 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('wants_to_learn', models.BooleanField(default=False, help_text='User wants to learn/register for training')),
                ('is_contacted', models.BooleanField(default=False, help_text='Has this enquiry been contacted?')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this enquiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, help_text='The training package this enquiry is about (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='training.trainingpackage')),
            ],
            options={
                'verbose_name': 'Training Enquiry',
                'verbose_name_plural': 'Training Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
